### ISSUE TITLE
Jackson mapping not working - e.g. leading to numerous NPEs / NoSuchElementException: No value present

### ISSUE THREAD

**Issue by MarkusTiede** [baloise-incubator/airlock-waf-kubernetes-openshift-integration#3]
```
Catch Kubernetes Routes event: cc [ADDED]
--
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
  | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
  | Building new Airlock WAF configuration...
  | [ResourceObject(type=configuration, id=68, attributes=null, relationships=null, links=null, meta=null), ResourceObject(type=configuration, id=14, attributes=null, relationships=null, links=null, meta=null), ResourceObject(type=configuration, id=2, attributes=null, relationships=null, links=null, meta=null), ResourceObject(type=configuration, id=1, attributes=null, relationships=null, links=null, meta=null)]
  | An unexpected error occurs: null
  | java.lang.NullPointerException
  | at com.airlock.waf.client.config.rs.client.ConfigurationRestApi.lambda$loadBaseConfig$0(ConfigurationRestApi.java:42)
  | at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
  | at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
  | at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  | at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
  | at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  | at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
  | at com.airlock.waf.client.config.rs.client.ConfigurationRestApi.loadBaseConfig(ConfigurationRestApi.java:47)
  | at com.airlock.waf.client.services.AirlockConfigurationService.update(AirlockConfigurationService.java:52)
  | at com.airlock.waf.client.RouteEventWatcher.lambda$run$0(RouteEventWatcher.java:44)
  | at java.lang.Iterable.forEach(Iterable.java:75)
  | at com.airlock.waf.client.RouteEventWatcher.run(RouteEventWatcher.java:38)
  | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
  | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
  | at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
  | at com.airlock.waf.client.Application.main(Application.java:16)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
  | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)


```

**Comment by orltom** [comment]
Hi Markus, it is a follow up issue after splitting the project in two modules. I forgot to change Jackson DTO Package Prefix: see following change: https://github.com/ergon/airlock-waf-kubernetes-openshift-integration/commit/fad030a8ef9bb22e1702cabdf8a4427f6fd6797e#diff-72fc31cc97f754e3929b00af00c3517fR81

or sync your fork repository.
